name: Linux (binary)

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
  LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev libpulse-dev
      - name: Update rust
        run: rustup update
      - name: Install cntp build tools
        run: |
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-bundle
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-deploy
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: |
          cargo cntp-bundle --no-open --verbose
          cargo cntp-deploy --no-open --verbose --output-file hummingbird-x86_64.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: hummingbird
          path: hummingbird-x86_64.AppImage
      - uses: softprops/action-gh-release@v2
        with:
          files: hummingbird-x86_64.AppImage
          prerelease: true
          name: latest
          tag_name: latest
